[default]
description = "Default permissions for the screentime plugin"
permissions = [
    "allow-request-authorization",
    "allow-check-authorization",
    "allow-block-websites",
    "allow-unblock-websites",
    "allow-block-apps",
    "allow-unblock-apps",
    "allow-refresh-activity-tokens",
    "allow-screentime-start-block",
    "allow-screentime-clear-block",
    "allow-schedule-block",
    "allow-set-schedules",
    "allow-unschedule-block",
    "allow-register-one-off-activity",
    "allow-set-resume-payload",
    "allow-set-block-end-state",
    "allow-show-activity-picker"
]
