[default]
description = "Default permissions for the android-blocker plugin"
permissions = [
    "allow-check-blocker-permissions",
    "allow-open-accessibility-settings",
    "allow-set-schedules",
    "allow-start-manual-block",
    "allow-stop-manual-block",
    "allow-read-native-schedules",
    "allow-get-schedule-states",
    "allow-get-cached-installed-apps",
    "allow-get-installed-apps",
    "allow-set-event-handler"
]
